os:
  - linux
language:
  - go
  - ruby
  - node_js
go: "1.13"
node_js: "node"

if: (tag =~ ^v) OR (tag =~ ^test) OR (branch = master) OR (branch == test)

env:
  global:
    - GO111MODULE=on
    - NAME=v2raya
    - VERSION=$(git describe --abbrev=0 --tags)
    - GOPROXY=https://goproxy.io
    - DESC="A V2Ray linux GUI client, which support transparent proxy .\nhttps://github.com/mzz2017/v2raya"
addons:
  apt:
    packages:
      - bsdtar
      - rpm
      - lintian
      - reprepro
      - gnupg
      - gnupg2
      - expect

install:
  - go get github.com/mitchellh/gox
  - gem install fpm
script:
  - cd service && gox -osarch="linux/386 linux/amd64 linux/arm linux/arm64" -ldflags="-X V2RayA/global.Version=${VERSION:1}" -output="../v2raya_{{.OS}}_{{.Arch}}_$VERSION"
  - cd ../
  - files="install/universal/v2raya.service=/etc/systemd/system/v2raya.service install/universal/v2raya.png=/usr/share/icons/v2raya.png install/universal/v2raya.desktop=/usr/share/applications/v2raya.desktop"
  - params="--verbose -f -n $NAME -v ${VERSION:1} --url https://github.com/mzz2017/v2raya --maintainer mzz2017 --after-install install/universal/after_install.sh --after-upgrade install/universal/after_upgrade.sh --before-remove install/universal/before_remove.sh --after-remove install/universal/after_remove.sh"
  - fpm -s dir -t deb -p installer_debian_i386_$VERSION.deb --description "$DESC" $params --architecture i386 v2raya_linux_386_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_amd64_$VERSION.deb --description "$DESC" $params --architecture=amd64 v2raya_linux_amd64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_armel_$VERSION.deb --description "$DESC" $params --architecture=armel v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_armhf_$VERSION.deb --description "$DESC" $params --architecture=armhf v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_arm64_$VERSION.deb --description "$DESC" $params --architecture=arm64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_i386_$VERSION.rpm --description "$DESC" $params --architecture=i386 v2raya_linux_386_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_amd64_$VERSION.rpm --description "$DESC" $params --architecture=amd64 v2raya_linux_amd64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_armel_$VERSION.rpm --description "$DESC" $params --architecture=armel v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_armhf_$VERSION.rpm --description "$DESC" $params --architecture=armhf v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_arm64_$VERSION.rpm --description "$DESC" $params --architecture=arm64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_i386_$VERSION.pkg.tar.xz --description "$DESC" $params --architecture=i386 v2raya_linux_386_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_amd64_$VERSION.pkg.tar.xz --description "$DESC" $params --architecture=amd64 v2raya_linux_amd64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_armel_$VERSION.pkg.tar.xz --description "$DESC" $params --architecture=armel v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_armhf_$VERSION.pkg.tar.xz --description "$DESC" $params --architecture=armhf v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_arm64_$VERSION.pkg.tar.xz --description "$DESC" $params --architecture=arm64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_i386_$VERSION.txz $params --description "$DESC" --architecture=i386 v2raya_linux_386_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_amd64_$VERSION.txz $params --description "$DESC" --architecture=amd64 v2raya_linux_amd64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_armel_$VERSION.txz $params --description "$DESC" --architecture=armel v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_armhf_$VERSION.txz $params --description "$DESC" --architecture=armhf v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_arm64_$VERSION.txz $params --description "$DESC" --architecture=arm64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - cd gui && yarn && yarn build && cd ../

before_deploy:
  if [[ $(pwd) =~ /apt$ ]]; then
      echo 'Now in subdir "apt"' &&
          cp -rf ../install/debian/key ../install/debian/conf ./;
  else
      mkdir -p apt/incoming && cp -r install/debian/key install/debian/conf apt/ && cd apt;
  fi &&
      gpg2 --import key/public-key.asc &&
      ../install/tool/gpg2_expect --allow-secret-key-import --import ../install/debian/private-key.asc &&
      ../install/tool/reprepro_expect --ask-passphrase -Vb . export &&
      ../install/tool/reprepro_expect --ask-passphrase -Vb . includedeb v2raya ../installer_debian_i386_$VERSION.deb &&
      ../install/tool/reprepro_expect --ask-passphrase -Vb . includedeb v2raya ../installer_debian_amd64_$VERSION.deb &&
      ../install/tool/reprepro_expect --ask-passphrase -Vb . includedeb v2raya ../installer_debian_armel_$VERSION.deb &&
      ../install/tool/reprepro_expect --ask-passphrase -Vb . includedeb v2raya ../installer_debian_armhf_$VERSION.deb &&
      ../install/tool/reprepro_expect --ask-passphrase -Vb . includedeb v2raya ../installer_debian_arm64_$VERSION.deb &&
      cp ../v2raya_linux_*_$VERSION pool/main/v/v2raya/ &&
      cd ../ &&
      export srcdir=$(pwd)

deploy:
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    keep_history: false
    repo: mzz2017/v2raya-apt
    target_branch: master
    local_dir: apt/
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    keep_history: false
    repo: mzz2017/v2raya-web
    target_branch: master
    local_dir: web/
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash install/aur/deploy.sh
    on:
      tags: true
  - provider: releases
    api_key:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    file:
      - "v2raya_linux_386_$VERSION"
      - "v2raya_linux_amd64_$VERSION"
      - "v2raya_linux_arm_$VERSION"
      - "v2raya_linux_arm64_$VERSION"
      - "installer_debian_i386_$VERSION.deb"
      - "installer_debian_amd64_$VERSION.deb"
      - "installer_debian_armel_$VERSION.deb"
      - "installer_debian_armhf_$VERSION.deb"
      - "installer_debian_arm64_$VERSION.deb"
      - "installer_freebsd_i386_$VERSION.txz"
      - "installer_freebsd_amd64_$VERSION.txz"
      - "installer_freebsd_armel_$VERSION.txz"
      - "installer_freebsd_armhf_$VERSION.txz"
      - "installer_freebsd_arm64_$VERSION.txz"
      - "installer_redhat_i386_$VERSION.rpm"
      - "installer_redhat_amd64_$VERSION.rpm"
      - "installer_redhat_armel_$VERSION.rpm"
      - "installer_redhat_armhf_$VERSION.rpm"
      - "installer_redhat_arm64_$VERSION.rpm"
      - "installer_archlinux_i386_$VERSION.pkg.tar.xz"
      - "installer_archlinux_amd64_$VERSION.pkg.tar.xz"
      - "installer_archlinux_armel_$VERSION.pkg.tar.xz"
      - "installer_archlinux_armhf_$VERSION.pkg.tar.xz"
      - "installer_archlinux_arm64_$VERSION.pkg.tar.xz"
    skip_cleanup: true
    draft: true
    overwrite: true
    on:
      tags: true
