os:
  - linux
dist: focal
language:
  - go
  - node_js
  - ruby
go:
  - 1.16.x

if: (tag =~ ^v) OR (tag =~ ^test) OR (branch = master) OR (branch == test) OR (branch == chore_travis)

env:
  global:
    - NODE_VERSION="lts/*"
    - GO111MODULE=on
    - NAME=v2raya
    - VERSION=$(git describe --abbrev=0 --tags)
    - GOPROXY=https://goproxy.io
    - DESC="A web GUI client of Project V which supports VMess, VLESS, SS, SSR, Trojan and Pingtunnel protocols."
    - P_DIR=$(pwd)
addons:
  apt:
    packages:
      - libarchive-tools
      - rpm
      - lintian
      - reprepro
      - gnupg
      - gnupg2
      - expect
      - tar
before_install:
  - nvm install $NODE_VERSION
install:
  - go get github.com/mitchellh/gox
  - gem install fpm -v 1.13.1
script:
  - yarn --cwd $P_DIR/gui && yarn --cwd $P_DIR/gui build
  - cd $P_DIR
  - tar -zcvf web.tar.gz web/
  - cp -r web $P_DIR/service/server/router/
  - cd $P_DIR/service && CGO_ENABLED=0 gox -ldflags '-extldflags "-static"' -osarch="linux/386 linux/amd64 linux/arm linux/arm64" -ldflags="-X github.com/v2rayA/v2rayA/global.Version=${VERSION:1} -s -w" -output="$P_DIR/v2raya_{{.OS}}_{{.Arch}}_$VERSION"
  - mv $P_DIR/v2raya_linux_386_$VERSION $P_DIR/v2raya_linux_x86_$VERSION && mv $P_DIR/v2raya_linux_amd64_$VERSION $P_DIR/v2raya_linux_x64_$VERSION
  - files="install/universal/v2raya.service=/etc/systemd/system/v2raya.service install/universal/v2raya.png=/usr/share/icons/hicolor/512x512/apps/v2raya.png install/universal/v2raya.desktop=/usr/share/applications/v2raya.desktop"
  - params="--verbose -f -n $NAME -v ${VERSION:1} --url https://github.com/v2rayA/v2raya --maintainer v2rayA --after-install install/universal/after_install.sh --after-upgrade $P_DIR/install/universal/after_upgrade.sh --before-remove $P_DIR/install/universal/before_remove.sh --after-remove $P_DIR/install/universal/after_remove.sh"
  - fpm -s dir -t deb -p installer_debian_x86_$VERSION.deb --description "$DESC" $params --architecture i386 v2raya_linux_x86_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_x64_$VERSION.deb --description "$DESC" $params --architecture=amd64 v2raya_linux_x64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_armel_$VERSION.deb --description "$DESC" $params --architecture=armel v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_armhf_$VERSION.deb --description "$DESC" $params --architecture=armhf v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_arm64_$VERSION.deb --description "$DESC" $params --architecture=arm64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t deb -p installer_debian_armv8_$VERSION.deb --description "$DESC" $params --architecture=armv8 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_x86_$VERSION.rpm --description "$DESC" $params --architecture=i386 v2raya_linux_x86_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_x64_$VERSION.rpm --description "$DESC" $params --architecture=amd64 v2raya_linux_x64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_armel_$VERSION.rpm --description "$DESC" $params --architecture=armel v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_armhf_$VERSION.rpm --description "$DESC" $params --architecture=armhf v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_aarch64_$VERSION.rpm --description "$DESC" $params --architecture=aarch64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t rpm -p installer_redhat_armv8_$VERSION.rpm --description "$DESC" $params --architecture=armv8 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_x86_$VERSION.pkg.tar.zstd --description "$DESC" $params --architecture=i386 v2raya_linux_x86_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_x64_$VERSION.pkg.tar.zstd --description "$DESC" $params --architecture=amd64 v2raya_linux_x64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_armel_$VERSION.pkg.tar.zstd --description "$DESC" $params --architecture=armel v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_armhf_$VERSION.pkg.tar.zstd --description "$DESC" $params --architecture=armhf v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_aarch64_$VERSION.pkg.tar.zstd --description "$DESC" $params --architecture=aarch64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_arm64_$VERSION.pkg.tar.zstd --description "$DESC" $params --architecture=arm64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t pacman -p installer_archlinux_armv8_$VERSION.pkg.tar.zstd --description "$DESC" $params --architecture=armv8 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_x86_$VERSION.txz $params --description "$DESC" --architecture=i386 v2raya_linux_x86_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_x64_$VERSION.txz $params --description "$DESC" --architecture=amd64 v2raya_linux_x64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_armel_$VERSION.txz $params --description "$DESC" --architecture=armel v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_armhf_$VERSION.txz $params --description "$DESC" --architecture=armhf v2raya_linux_arm_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_aarch64_$VERSION.txz $params --description "$DESC" --architecture=aarch64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_arm64_$VERSION.txz $params --description "$DESC" --architecture=arm64 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files
  - fpm -s dir -t freebsd -p installer_freebsd_armv8_$VERSION.txz $params --description "$DESC" --architecture=armv8 v2raya_linux_arm64_$VERSION=/usr/bin/v2raya $files

before_deploy: |
  mkdir -p $P_DIR/apt/incoming && cp -r $P_DIR/install/debian/key $P_DIR/install/debian/conf $P_DIR/apt/ &&
  gpg2 --import $P_DIR/apt/key/public-key.asc &&
  $P_DIR/install/tool/gpg2_expect --allow-secret-key-import --import $P_DIR/install/debian/private-key.asc &&
  $P_DIR/install/tool/reprepro_expect --ask-passphrase -Vb $P_DIR/apt includedeb v2raya $P_DIR/installer_debian_*_$VERSION.deb &&
  $P_DIR/install/tool/reprepro_expect --ask-passphrase -Vb $P_DIR/apt export &&
  cp $P_DIR/v2raya_linux_*_$VERSION $P_DIR/apt/pool/main/v/v2raya/ &&
  cp $P_DIR/web.tar.gz $P_DIR/apt/pool/main/v/v2raya/web_$VERSION.tar.gz &&
  echo "apt.v2raya.mzz.pub" > $P_DIR/apt/CNAME &&
  cd $P_DIR

deploy:
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    keep_history: false
    repo: v2rayA/v2raya-apt
    target_branch: master
    local_dir: $P_DIR/apt/
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    keep_history: false
    repo: v2rayA/v2raya-web
    target_branch: master
    local_dir: $P_DIR/web/
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash install/aur/deploy.sh
    on:
      tags: true
  - provider: releases
    api_key:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    file:
      - "v2raya_linux_x86_$VERSION"
      - "v2raya_linux_x64_$VERSION"
      - "v2raya_linux_arm_$VERSION"
      - "v2raya_linux_arm64_$VERSION"
      - "installer_debian_x86_$VERSION.deb"
      - "installer_debian_x64_$VERSION.deb"
      - "installer_debian_armel_$VERSION.deb"
      - "installer_debian_armhf_$VERSION.deb"
      - "installer_debian_arm64_$VERSION.deb"
      - "installer_debian_armv8_$VERSION.deb"
      - "installer_freebsd_x86_$VERSION.txz"
      - "installer_freebsd_x64_$VERSION.txz"
      - "installer_freebsd_armel_$VERSION.txz"
      - "installer_freebsd_armhf_$VERSION.txz"
      - "installer_freebsd_aarch64_$VERSION.txz"
      - "installer_freebsd_arm64_$VERSION.txz"
      - "installer_freebsd_armv8_$VERSION.txz"
      - "installer_redhat_x86_$VERSION.rpm"
      - "installer_redhat_x64_$VERSION.rpm"
      - "installer_redhat_armel_$VERSION.rpm"
      - "installer_redhat_armhf_$VERSION.rpm"
      - "installer_redhat_aarch64_$VERSION.rpm"
      - "installer_redhat_armv8_$VERSION.rpm"
      - "installer_archlinux_x86_$VERSION.pkg.tar.zstd"
      - "installer_archlinux_x64_$VERSION.pkg.tar.zstd"
      - "installer_archlinux_armel_$VERSION.pkg.tar.zstd"
      - "installer_archlinux_armhf_$VERSION.pkg.tar.zstd"
      - "installer_archlinux_aarch64_$VERSION.pkg.tar.zstd"
      - "installer_archlinux_arm64_$VERSION.pkg.tar.zstd"
      - "installer_archlinux_armv8_$VERSION.pkg.tar.zstd"
    skip_cleanup: true
    draft: true
    overwrite: true
    on:
      tags: true

after_deploy: |
  curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache" \
  -H "X-Auth-Email: $CF_AUTH_EMAIL" \
  -H "Authorization: Bearer $CF_PARGE_CACHE_AUTH_KEY" \
  -H "Content-Type: application/json" \
  --data '{"purge_everything":true}'
