os:
  - linux
language:
  - go
  - ruby
  - node_js
go: "1.12"

if: (tag =~ ^v) OR (tag =~ ^test) OR (branch = master) OR (branch == test)

env:
  global:
    - GO111MODULE=on
    - NAME=v2raya
    - VERSION=$(git describe --abbrev=0 --tags)
    - GOPROXY=https://goproxy.io
addons:
  apt:
    packages:
      - bsdtar
      - rpm
      - lintian
      - reprepro
      - gnupg
      - gnupg2
      - expect

install:
  - go get github.com/mitchellh/gox
  - gem install fpm
script:
  - cd service && gox -osarch="linux/amd64 linux/arm" -ldflags="-X V2RayA/global.Version=${VERSION:1}" -output="../{{.Dir}}_{{.OS}}_{{.Arch}}_$VERSION"
  - cd ../
  - files="V2RayA_linux_amd64_$VERSION=/usr/bin/v2raya install/v2raya.service=/etc/systemd/system/v2raya.service"
  - params="--verbose -f -n $NAME -v ${VERSION:1} --after-install=install/after_install.sh --before-remove=install/before_remove.sh --after-remove=install/after_remove.sh --after-upgrade=install/after_upgrade.sh $files"
  - echo $params
  - fpm -s dir -t deb -p installer_debian_$VERSION.deb $params && fpm -s dir -t rpm -p installer_redhat_$VERSION.rpm $params && fpm -s dir -t pacman -p installer_arch_$VERSION.pkg.tar.xz $params && fpm -s dir -t freebsd -p installer_freebsd_$VERSION.txz $params
  - cd gui && yarn && yarn build && cd ../

before_deploy:
  if [[ $(pwd) =~ /apt$ ]]; then
      echo 'Now in subdir "apt"' &&
          cp -rf ../install/key ../install/conf ./;
  else
      mkdir -p apt/incoming && cp -r install/key install/conf apt/ && cd apt;
  fi &&
      gpg2 --import key/public-key.asc &&
      ../install/gpg2_expect --allow-secret-key-import --import ../install/private-key.asc &&
      ../install/reprepro_expect --ask-passphrase -Vb . export &&
      ../install/reprepro_expect --ask-passphrase -Vb . includedeb v2raya ../installer_debian_$VERSION.deb &&
      cd ../ && 
      export bp=$(pwd)

deploy:
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    keep_history: false
    target_branch: apt
    local_dir: apt/
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    keep_history: false
    repo: mzz2017/v2raya-web
    target_branch: master
    local_dir: web/
    on:
      tags: true
  - provider: releases
    api_key:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    file:
      - "V2RayA_linux_amd64_$VERSION"
      - "V2RayA_linux_arm_$VERSION"
      - "installer_debian_$VERSION.deb"
      - "installer_freebsd_$VERSION.txz"
      - "installer_redhat_$VERSION.rpm"
      - "installer_arch_$VERSION.pkg.tar.xz"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: script
    script: bash install/aur.sh
    on:
      tags: true
