name: Release Windows build

on:
  push:
    branches: [ feat_v5 ]
    tags:
      - v*
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "gui/**"
      - ".github/workflows/*.yml"
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare
        shell: bash
        id: prep
        env:
          REF: ${{ github.ref }}
        run: |
          echo "name=P_DIR::$(pwd)" >> $GITHUB_OUTPUT
          if [[ "$REF" == "refs/tags/v"* ]]; then
            tag=$(git describe --tags $(git rev-list --tags --max-count=1))
            version=${tag:1}
          else
            date=$(git log -1 --format="%cd" --date=short | sed s/-//g)
            count=$(git rev-list --count HEAD)
            commit=$(git rev-parse --short HEAD)
            version="unstable-$date.r${count}.$commit"
          fi
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Add PowerShell
        uses: Amadevus/pwsh-script@v2.0.3
      - name: Install Inno Setup
        run: |
          choco install innosetup -y
      - name: build v2rayA installer
        shell: pwsh
        run: |
          pwsh -c ./install/windows-inno/build-helper.ps1
      - name: Rename to friendly name
        shell: bash
        run: |
          mv installer_windows_inno_x64.exe installer_windows_inno_x64_${{ steps.prep.outputs.VERSION }}.exe
          mv installer_windows_inno_arm64.exe installer_windows_inno_arm64_${{ steps.prep.outputs.VERSION }}.exe
      - name: Upload Artifact
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: nanoufo/action-upload-artifacts-and-release-assets@v1.5
        with:
          path: |
            installer_windows_inno_x64_${{ steps.prep.outputs.VERSION }}.exe
            installer_windows_inno_arm64_${{ steps.prep.outputs.VERSION }}.exe
            v2raya_windows_x64_${{ steps.prep.outputs.VERSION }}.exe
            v2raya_windows_arm64_${{ steps.prep.outputs.VERSION }}.exe
      - name: Github Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          files: |
            installer_windows_inno_x64_${{ steps.prep.outputs.VERSION }}.exe
            installer_windows_inno_arm64_${{ steps.prep.outputs.VERSION }}.exe
            v2raya_windows_arm64_${{ steps.prep.outputs.VERSION }}.exe
            v2raya_windows_x64_${{ steps.prep.outputs.VERSION }}.exe
      - name: Submit to Winget
        if: startsWith(github.ref, 'refs/tags/v')
        shell: pwsh
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          Start-Sleep -Seconds 30 #Make sure GitHub releases are online
          $Installer_x64_url = "https://github.com/v2rayA/v2rayA/releases/download/v${{ steps.prep.outputs.VERSION }}/installer_windows_inno_x64_${{ steps.prep.outputs.VERSION }}.exe"
          $Installer_ARM64_url = "https://github.com/v2rayA/v2rayA/releases/download/v${{ steps.prep.outputs.VERSION }}/installer_windows_inno_arm64_${{ steps.prep.outputs.VERSION }}.exe"
          ./wingetcreate.exe update v2rayA.v2rayA --urls $Installer_x64_url $Installer_ARM64_url --version ${{ steps.prep.outputs.VERSION }} --token ${{ secrets.GITHUB_TOKEN }} --submit